package com.linexstudios.foxtrot.Handler;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class PitDataHandler {

    private static final Map<String, PrestigeData> PRESTIGES = new HashMap<>();
    private static final List<PitEnchant> ENCHANTS = new ArrayList<>();

    static {
        // Prestige Data
        addPrestige("0", "1×", "65,950", "65,950", "10,000", "gray", "GRAY");
        addPrestige("I", "1.1×", "72,560", "138,510", "20,000", "blue", "BLUE");
        addPrestige("II", "1.2×", "79,170", "217,680", "20,000", "blue", "BLUE");
        addPrestige("III", "1.3×", "85,750", "303,430", "20,000", "blue", "BLUE");
        addPrestige("IV", "1.4×", "92,330", "395,760", "30,000", "blue", "BLUE");
        addPrestige("V", "1.5×", "98,940", "494,700", "35,000", "yellow", "YELLOW");
        addPrestige("VI", "1.75×", "115,440", "610,140", "40,000", "yellow", "YELLOW");
        addPrestige("VII", "2×", "131,900", "742,040", "45,000", "yellow", "YELLOW");
        addPrestige("VIII", "2.5×", "164,890", "906,930", "50,000", "yellow", "YELLOW");
        addPrestige("IX", "3×", "197,850", "1,104,780", "60,000", "yellow", "YELLOW");
        addPrestige("X", "4×", "263,800", "1,368,580", "70,000", "orange", "GOLD");
        addPrestige("XI", "5×", "329,750", "1,698,330", "80,000", "orange", "GOLD");
        addPrestige("XII", "6×", "395,700", "2,094,030", "90,000", "orange", "GOLD");
        addPrestige("XIII", "7×", "461,650", "2,555,680", "100,000", "orange", "GOLD");
        addPrestige("XIV", "8×", "527,600", "3,083,280", "125,000", "orange", "GOLD");
        addPrestige("XV", "9×", "593,550", "3,676,830", "150,000", "red", "RED");
        addPrestige("XVI", "10×", "659,500", "4,336,330", "175,000", "red", "RED");
        addPrestige("XVII", "12×", "791,400", "5,127,730", "200,000", "red", "RED");
        addPrestige("XVIII", "14×", "923,300", "6,051,030", "250,000", "red", "RED");
        addPrestige("XIX", "16×", "1,055,200", "7,106,230", "300,000", "red", "RED");
        addPrestige("XX", "18×", "1,187,100", "8,293,330", "350,000", "purple", "DARK_PURPLE");
        addPrestige("XXI", "20×", "1,319,000", "9,612,330", "400,000", "purple", "DARK_PURPLE");
        addPrestige("XXII", "24×", "1,582,800", "11,195,130", "500,000", "purple", "DARK_PURPLE");
        addPrestige("XXIII", "28×", "1,846,600", "13,041,730", "600,000", "purple", "DARK_PURPLE");
        addPrestige("XXIV", "32×", "2,110,400", "15,152,130", "700,000", "purple", "DARK_PURPLE");
        addPrestige("XXV", "36×", "2,374,200", "17,526,330", "800,000", "pink", "LIGHT_PURPLE");
        addPrestige("XXVI", "40×", "2,638,000", "20,164,330", "900,000", "pink", "LIGHT_PURPLE");
        addPrestige("XXVII", "45×", "2,967,750", "23,132,080", "1,000,000", "pink", "LIGHT_PURPLE");
        addPrestige("XXVIII", "50×", "3,297,500", "26,429,580", "1,000,000", "pink", "LIGHT_PURPLE");
        addPrestige("XXIX", "75×", "4,946,250", "31,375,830", "1,000,000", "pink", "LIGHT_PURPLE");
        addPrestige("XXX", "100×", "6,595,000", "37,970,830", "1,000,000", "white", "WHITE");
        addPrestige("XXXI", "101×", "6,660,950", "44,631,780", "1,000,000", "white", "WHITE");
        addPrestige("XXXII", "101×", "6,660,950", "51,292,730", "1,000,000", "white", "WHITE");
        addPrestige("XXXIII", "101×", "6,660,950", "57,953,680", "1,000,000", "white", "WHITE");
        addPrestige("XXXIV", "101×", "6,660,950", "64,614,630", "1,000,000", "white", "WHITE");
        addPrestige("XXXV", "101×", "6,660,950", "71,275,580", "2,000,000", "aqua", "AQUA");
        addPrestige("XXXVI", "200×", "13,190,000", "84,465,580", "2,000,000", "aqua", "AQUA");
        addPrestige("XXXVII", "300×", "19,785,000", "104,250,580", "2,000,000", "aqua", "AQUA");
        addPrestige("XXXVIII", "400×", "26,380,000", "130,630,580", "2,000,000", "aqua", "AQUA");
        addPrestige("XXXIX", "500×", "32,975,000", "163,605,580", "2,000,000", "aqua", "AQUA");
        addPrestige("XL", "750×", "49,462,500", "213,068,080", "2,000,000", "dark blue", "DARK_BLUE");
        addPrestige("XLI", "1,000×", "65,950,000", "279,018,080", "2,000,000", "dark blue", "DARK_BLUE");
        addPrestige("XLII", "1,250×", "82,437,500", "361,455,580", "2,000,000", "dark blue", "DARK_BLUE");
        addPrestige("XLIII", "1,500×", "98,925,000", "460,380,580", "2,000,000", "dark blue", "DARK_BLUE");
        addPrestige("XLIV", "1,750×", "115,412,500", "575,793,080", "2,000,000", "dark blue", "DARK_BLUE");
        addPrestige("XLV", "2,000×", "131,900,000", "707,693,080", "2,000,000", "black", "BLACK");
        addPrestige("XLVI", "3,000×", "197,850,000", "905,543,080", "2,000,000", "black", "BLACK");
        addPrestige("XLVII", "5,000×", "329,750,000", "1,235,293,080", "2,000,000", "black", "BLACK");
        addPrestige("XLVIII", "10,000×", "659,500,000", "1,894,793,080", "2,000,000", "dark red", "DARK_RED");
        addPrestige("XLIX", "50,000×", "3,297,500,000", "5,192,293,080", "2,000,000", "dark red", "DARK_RED");
        addPrestige("L", "100,000×", "6,595,000,000", "11,787,293,080", "N/A", "dark gray", "DARK_GRAY");

        // Enchant Data
        addEnchant("Ace of Spades", "I", false, "Take 0.5♥︎ less damage from Combat Spades .");
        addEnchant("Ace of Spades", "II", false, "Take 1.0♥︎ less damage from Combat Spades .");
        addEnchant("Ace of Spades", "III", false, "Take 1.5♥︎ less damage from Combat Spades .");
        addEnchant("Brakes!", "I", false, "If the target has a level of Speed higher than I, set it to I.");
        addEnchant("Brakes!", "II", false, "If the target has a level of Speed higher than I, set it to I. Take −5% damage from players at a higher elevation than yourself.");
        addEnchant("Brakes!", "III", false, "If the target has a level of Speed higher than I, set it to I. Take −10% damage from players at a higher elevation than yourself.");
        addEnchant("Combo: Breaching Charge", "I", false, "Every 4 hits removes the Resistance effect from the target.");
        addEnchant("Combo: Breaching Charge", "II", false, "Every 3 hits removes the Resistance effect from the target.");
        addEnchant("Combo: Breaching Charge", "III", false, "Every 2 hits removes the Resistance effect from the target.");
        addEnchant("Do it like the French", "I", false, "Deal 0.5♥︎ more damage to players wearing Golden Helmets .");
        addEnchant("Do it like the French", "II", false, "Deal 1.0♥︎ more damage to players wearing Golden Helmets .");
        addEnchant("Do it like the French", "III", false, "Deal 1.5♥︎ more damage to players wearing Golden Helmets .");
        addEnchant("Heigh-Ho", "I", false, "Deal 0.5♥︎ more damage to players wearing pants with Mirror .");
        addEnchant("Heigh-Ho", "II", false, "Deal 1.0♥︎ more damage to players wearing pants with Mirror .");
        addEnchant("Heigh-Ho", "III", false, "Deal 1.5♥︎ more damage to players wearing pants with Mirror .");
        addEnchant("New Deal", "I", false, "Gain immunity to the Billionaire enchantment.");
        addEnchant("New Deal", "II", false, "Gain immunity to the Billionaire enchantment. Take −4% less damage from all sources.");
        addEnchant("New Deal", "III", false, "Gain immunity to the Billionaire enchantment. Take −8% less damage from all sources.");
        addEnchant("Really Toxic", "I", false, "Hits apply stacks of toxicity for 30 seconds. Toxicity stacks reduce the target's healing by 2% per stack. Max 10 stacks.");
        addEnchant("Really Toxic", "II", false, "Hits apply stacks of toxicity for 30 seconds. Toxicity stacks reduce the target's healing by 2% per stack. Max 15 stacks.");
        addEnchant("Really Toxic", "III", false, "Hits apply stacks of toxicity for 30 seconds. Toxicity stacks reduce the target's healing by 2% per stack. Max 20 stacks.");
        addEnchant("Sybil", "I", false, "Count as 2 players to enchants and perks (excluding Shark ).");
        addEnchant("Sybil", "II", false, "Count as 3 players to enchants and perks (excluding Shark ).");
        addEnchant("Sybil", "III", false, "Count as 4 players to enchants and perks (excluding Shark ).");
        addEnchant("Regularity", "I", true, "If your melee attack deals less than 1.1♥︎ damage, automatically strike again in 0.1s. The second strike hits for 45% of the first hit's damage.");
        addEnchant("Regularity", "II", true, "If your melee attack deals less than 1.3♥︎ damage, automatically strike again in 0.1s. The second strike hits for 60% of the first hit's damage.");
        addEnchant("Regularity", "III", true, "If your melee attack deals less than 1.5♥︎ damage, automatically strike again in 0.1s. The second strike hits for 75% of the first hit's damage.");
        addEnchant("Think of the People", "I", true, "Players within 10 blocks gain immunity to Executioner and Combo: Perun's Wrath .");
        addEnchant("Think of the People", "II", true, "Players within 10 blocks gain immunity to Executioner and Combo: Perun's Wrath . They also take −10% damage from weapons with these enchantments.");
        addEnchant("Think of the People", "III", true, "Players within 10 blocks gain immunity to Executioner and Combo: Perun's Wrath . They also take −20% damage from weapons with these enchantments.");
        addEnchant("Deal with the Devil", "I", true, "The Devil Chicks enchantment is disabled in the entire lobby while worn.");
        addEnchant("Deal with the Devil", "II", true, "The Devil Chicks enchantment is disabled in the entire lobby while worn. User deals +5% damage in Rage Pit .");
        addEnchant("Deal with the Devil", "III", true, "The Devil Chicks enchantment is disabled in the entire lobby while worn. User deals +10% damage in Rage Pit .");
        addEnchant("Billy", "I", false, "Receive −2% damage per 1,000g in your bounty. Capped at −10% ( 5,000g bounty).");
        addEnchant("Billy", "II", false, "Receive −3% damage per 1,000g in your bounty. Capped at −15% ( 5,000g bounty).");
        addEnchant("Billy", "III", false, "Receive −4% damage per 1,000g in your bounty. Capped at −20% ( 5,000g bounty).");
        addEnchant("Cricket", "I", false, "Receive −5% damage while you or your attacker is standing on grass. Permanent Regeneration I on grass.");
        addEnchant("Cricket", "II", false, "Receive −7% damage while you or your attacker is standing on grass. Permanent Regeneration I on grass.");
        addEnchant("Cricket", "III", false, "Receive −15% damage while you or your attacker is standing on grass. Permanent Regeneration I on grass.");
        addEnchant("David and Goliath", "I", false, "Receive −15% damage from players with a bounty.");
        addEnchant("David and Goliath", "II", false, "Receive −25% damage from players with a bounty.");
        addEnchant("David and Goliath", "III", false, "Receive −40% damage from players with a bounty.");
        addEnchant("Diamond Allergy", "I", false, "Receive −10% damage from diamond weapons.");
        addEnchant("Diamond Allergy", "II", false, "Receive −20% damage from diamond weapons.");
        addEnchant("Diamond Allergy", "III", false, "Receive −30% damage from diamond weapons.");
        addEnchant("McSwimmer", "I", false, "Receive −25% damage when in water or lava. Cannot drown.");
        addEnchant("McSwimmer", "II", false, "Receive −40% damage when in water or lava. Cannot drown.");
        addEnchant("McSwimmer", "III", false, "Receive −60% damage when in water or lava. Cannot drown.");
        addEnchant("\"Not\" Gladiator", "I", false, "Receive −1% damage per player within 10 blocks, up to 10 players.");
        addEnchant("\"Not\" Gladiator", "II", false, "Receive −1.5% damage per player within 10 blocks, up to 10 players.");
        addEnchant("\"Not\" Gladiator", "III", false, "Receive −2% damage per player within 10 blocks, up to 10 players.");
        addEnchant("Protection", "I", false, "Receive −4% damage.");
        addEnchant("Protection", "II", false, "Receive −6% damage.");
        addEnchant("Protection", "III", false, "Receive −10% damage.");
        addEnchant("Ring Armor", "I", false, "Receive −20% damage from arrows.");
        addEnchant("Ring Armor", "II", false, "Receive −40% damage from arrows.");
        addEnchant("Ring Armor", "III", false, "Receive −60% damage from arrows.");
        addEnchant("Sweaty", "I", false, "Increase the streak XP bonus by 20% .");
        addEnchant("Sweaty", "II", false, "Increase the streak XP bonus by 40% . +50 max XP on kill.");
        addEnchant("Sweaty", "III", false, "Increase the streak XP bonus by 60% . +100 max XP on kill.");
        addEnchant("XP Boost", "I", false, "Earn +10% XP on kills and assists.");
        addEnchant("XP Boost", "II", false, "Earn +20% XP on kills and assists.");
        addEnchant("XP Boost", "III", false, "Earn +30% XP on kills and assists.");
        addEnchant("XP Bump", "I", false, "Earn +2 XP on kill and a reduced amount on assist.");
        addEnchant("XP Bump", "II", false, "Earn +4 XP on kill and a reduced amount on assist.");
        addEnchant("XP Bump", "III", false, "Earn +6 XP on kill and a reduced amount on assist.");
        addEnchant("Critically Rich", "I", false, "Earn +2 gold on critical hits.");
        addEnchant("Critically Rich", "II", false, "Earn +4 gold on critical hits.");
        addEnchant("Critically Rich", "III", false, "Earn +6 gold on critical hits.");
        addEnchant("Gold Boost", "I", false, "Earn +15% gold from kills and assists.");
        addEnchant("Gold Boost", "II", false, "Earn +30% gold from kills and assists.");
        addEnchant("Gold Boost", "III", false, "Earn +45% gold from kills and assists.");
        addEnchant("Gold Bump", "I", false, "Earn +4 gold on kill and a reduced amount on assist.");
        addEnchant("Gold Bump", "II", false, "Earn +8 gold on kill and a reduced amount on assist.");
        addEnchant("Gold Bump", "III", false, "Earn +12 gold on kill and a reduced amount on assist.");
        addEnchant("Lodbrok", "I", false, "Chance to drop armor from opponents increases from 30% to 40%.");
        addEnchant("Lodbrok", "II", false, "Chance to drop armor from opponents increases from 30% to 55%.");
        addEnchant("Lodbrok", "III", false, "Chance to drop armor from opponents increases from 30% to 75%.");
        addEnchant("Moctezuma", "I", false, "Earn +6 gold on kills.");
        addEnchant("Moctezuma", "II", false, "Earn +12 gold on kills.");
        addEnchant("Moctezuma", "III", false, "Earn +18 gold on kills.");
        addEnchant("Negotiator", "I", false, "Earn +30% gold when completing contracts.");
        addEnchant("Negotiator", "II", false, "Earn +60% gold when completing contracts.");
        addEnchant("Negotiator", "III", false, "Earn +100% gold when completing contracts.");
        addEnchant("Pebble", "I", false, "Earn +10 gold from ingot pickups.");
        addEnchant("Pebble", "II", false, "Earn +20 gold from ingot pickups.");
        addEnchant("Pebble", "III", false, "Earn +30 gold and 1♥︎ absorption (max of 4♥︎ ) from ingot pickups.");
        addEnchant("Purple Gold", "I", false, "Breaking obsidian rewards 7 gold . Blocks mined with the Golden Pickaxe do not reward gold .");
        addEnchant("Purple Gold", "II", false, "Breaking obsidian rewards 11 gold and Regeneration III (0:02). Blocks mined with the Golden Pickaxe do not reward gold or regeneration.");
        addEnchant("Purple Gold", "III", false, "Breaking obsidian rewards 15 gold and Regeneration III (0:03). Blocks mined with the Golden Pickaxe do not reward gold or regeneration.");
        addEnchant("Self-checkout", "I", false, "If you have a 5,000g bounty or higher, remove it, earn 2,000g , and consume 1 life of this item.");
        addEnchant("Self-checkout", "II", false, "If you have a 5,000g bounty or higher, remove it, earn 3,000g , and consume 1 life of this item.");
        addEnchant("Self-checkout", "III", false, "If you have a 5,000g bounty or higher, remove it, earn 5,000g , and consume 1 life of this item.");
        addEnchant("Strike Gold", "I", false, "Earn +1 gold on hit. 1 second cooldown.");
        addEnchant("Strike Gold", "II", false, "Earn +2 gold on hit. 1 second cooldown.");
        addEnchant("Strike Gold", "III", false, "Earn +3 gold on hit. 1 second cooldown.");
        addEnchant("Pants Radar", "I", false, "30% higher chance to find mystic items on kill.");
        addEnchant("Pants Radar", "II", false, "60% higher chance to find mystic items on kill.");
        addEnchant("Pants Radar", "III", false, "90% higher chance to find mystic items on kill.");
        addEnchant("Boo-boo", "I", false, "Passively heal 1♥︎ every 5 seconds.");
        addEnchant("Boo-boo", "II", false, "Passively heal 1♥︎ every 4 seconds.");
        addEnchant("Boo-boo", "III", false, "Passively heal 1♥︎ every 3 seconds.");
        addEnchant("Counter-Offensive", "I", false, "Gain Speed II (0:03) when hit four times.");
        addEnchant("Counter-Offensive", "II", false, "Gain Speed II (0:05) when hit three times.");
        addEnchant("Counter-Offensive", "III", false, "Gain Speed II (0:07) when hit two times.");
        addEnchant("Creative", "I", false, "Spawn with 16 placeable oak planks. Gain 6 planks on kill. Planks last for 30 seconds by default. Max 64 held.");
        addEnchant("Creative", "II", false, "Spawn with 32 placeable oak planks. Gain 12 planks on kill. Planks last for 30 seconds by default. Max 64 held.");
        addEnchant("Creative", "III", false, "Spawn with 48 placeable oak planks. Gain 18 planks on kill. Planks last for 30 seconds by default. Max 64 held.");
        addEnchant("Critically Funky", "I", false, "Take −20% damage from critical hits.");
        addEnchant("Critically Funky", "II", false, "Take −35% damage from critical hits. Taking a critical hit increases your next strike's damage by 14% .");
        addEnchant("Critically Funky", "III", false, "Take −50% damage from critical hits. Taking a critical hit increases your next strike's damage by 30% .");
        addEnchant("Danger Close", "I", false, "Gain Speed III (0:03) when reaching 3♥︎ left. 10 second cooldown.");
        addEnchant("Danger Close", "II", false, "Gain Speed III (0:06) when reaching 4♥︎ left. 10 second cooldown.");
        addEnchant("Danger Close", "III", false, "Gain Speed III (0:09) when reaching 4♥︎ left. 10 second cooldown.");
        addEnchant("Eggs", "I", false, "Spawn with 8 eggs. Gain 4 on kill. Max 16.");
        addEnchant("Eggs", "II", false, "Spawn with 8 eggs. Gain 8 on kill. Max 16.");
        addEnchant("Eggs", "III", false, "Spawn with 16 eggs. Gain 16 on kill. Max 16.");
        addEnchant("Electrolytes", "I", false, "If you have Speed I on kill, add 2 seconds to it. If you have Speed II or higher, add 1 second instead.");
        addEnchant("Electrolytes", "II", false, "If you have Speed I on kill, add 4 seconds to it. If you have Speed II or higher, add 2 seconds instead.");
        addEnchant("Electrolytes", "III", false, "If you have Speed I on kill, add 6 seconds to it. If you have Speed II or higher, add 3 seconds instead.");
        addEnchant("Excess", "I", false, "+1 max healing item. Applies after the effects of Overheal .");
        addEnchant("Excess", "II", false, "+2 max healing items. Applies after the effects of Overheal .");
        addEnchant("Excess", "III", false, "+3 max healing items. Applies after the effects of Overheal .");
        addEnchant("Golden Heart", "I", false, "Gain 0.5♥︎ Absorption on kill. Max 4♥︎ .");
        addEnchant("Golden Heart", "II", false, "Gain 1♥︎ Absorption on kill. Max 5♥︎ .");
        addEnchant("Golden Heart", "III", false, "Gain 2♥︎ Absorption on kill. Max 6♥︎ .");
        addEnchant("Gotta go fast", "I", false, "Move 5% [bug] In-game description states +4%. faster. A white particle trail appears as you run.");
        addEnchant("Gotta go fast", "II", false, "Move 10% faster. A white particle trail appears as you run.");
        addEnchant("Gotta go fast", "III", false, "Move 20% faster. A white particle trail appears as you run.");
        addEnchant("Hearts", "I", false, "Gain 0.25♥︎ max health.");
        addEnchant("Hearts", "II", false, "Gain 0.5♥︎ max health.");
        addEnchant("Hearts", "III", false, "Gain 1♥︎ max health.");
        addEnchant("Hunt the Hunter", "I", false, "Players using the Bounty Hunter perk deal only half of their bonus damage to you. This mystic is disabled when using the Highlander megastreak.");
        addEnchant("Hunt the Hunter", "II", false, "Players using the Bounty Hunter perk do not deal bonus damage to you. This mystic is disabled when using the Highlander megastreak.");
        addEnchant("Hunt the Hunter", "III", false, "Players using the Bounty Hunter perk do not deal bonus damage to you and deal overall −20% damage to you. This mystic is disabled when using the Highlander megastreak.");
        addEnchant("Last Stand", "I", false, "Gain Resistance I (0:03) when reaching 3♥︎ left. 10 second cooldown.");
        addEnchant("Last Stand", "II", false, "Gain Resistance II (0:04) when reaching 3♥︎ left. 10 second cooldown.");
        addEnchant("Last Stand", "III", false, "Gain Resistance III (0:04) when reaching 3♥︎ left. 10 second cooldown.");
        addEnchant("Mirror", "I", false, "You are immune to true damage .");
        addEnchant("Mirror", "II", false, "You are immune to true damage and reflect 25% of it taken to the attacker.");
        addEnchant("Mirror", "III", false, "You are immune to true damage and reflect 50% of it taken to the attacker.");
        addEnchant("Peroxide", "I", false, "Heal 0.5♥︎ when hit. 1.5s cooldown.");
        addEnchant("Peroxide", "II", false, "Heal 0.7♥︎ when hit. 1.5s cooldown.");
        addEnchant("Peroxide", "III", false, "Heal 1♥︎ when hit. 1.5s cooldown.");
        addEnchant("Prick", "I", false, "When attacked, deal 0.25♥︎ of true damage to your attacker.");
        addEnchant("Prick", "II", false, "When attacked, deal 0.375♥︎ of true damage to your attacker.");
        addEnchant("Prick", "III", false, "When attacked, deal 0.5♥︎ of true damage to your attacker.");
        addEnchant("Respawn: Absorption", "I", false, "Respawn with 5♥︎ of absorption.");
        addEnchant("Respawn: Absorption", "II", false, "Respawn with 10♥︎ of absorption.");
        addEnchant("Respawn: Absorption", "III", false, "Respawn with 15♥︎ of absorption.");
        addEnchant("Respawn: Resistance", "I", false, "When returning to spawn, gain Resistance I (0:20). Effect timer counts down even while in spawn and is removed if these pants are removed.");
        addEnchant("Respawn: Resistance", "II", false, "When returning to spawn, gain Resistance I (0:30). Effect timer counts down even while in spawn and is removed if these pants are removed.");
        addEnchant("Respawn: Resistance", "III", false, "When returning to spawn, gain Resistance II (0:40). Effect timer counts down even while in spawn and is removed if these pants are removed.");
        addEnchant("Revitalize", "I", false, "Gain Speed I (0:05) and Regeneration II (0:03) when you have 3♥︎ left. 45 second cooldown.");
        addEnchant("Revitalize", "II", false, "Gain Speed II (0:05) and Regeneration III (0:03) when you have 3♥︎ left. 45 second cooldown.");
        addEnchant("Revitalize", "III", false, "Gain Speed II (0:07) and Regeneration III (0:05) when you have 3♥︎ left. 45 second cooldown.");
        addEnchant("Steaks", "I", false, "Gain Tasty Steak on kill instead of golden apples. Grants 2♥︎ absorption, Regeneration III (0:04), and 4% damage (stacking) for 50 seconds. Can hold up to 8 steaks.");
        addEnchant("Steaks", "II", false, "Gain Tasty Steak on kill instead of golden apples. Grants 2♥︎ absorption, Regeneration III (0:04), and 4% damage (stacking) for 50 seconds. Can hold up to 10 steaks.");
        addEnchant("Steaks", "III", false, "Gain Tasty Steak on kill instead of golden apples. Grants 2♥︎ absorption, Regeneration III (0:04), and 4% damage (stacking) for 50 seconds. Can hold up to 12 steak.");
        addEnchant("TNT", "I", false, "Spawn with 1 TNT. Gain 1 TNT on kill. TNT explodes 1.5 seconds after placement, dealing 1♥︎ of true damage to all players in the explosion. Max 7 held.");
        addEnchant("TNT", "II", false, "Spawn with 2 TNT. Gain 1 TNT on kill. TNT explodes 1.5 seconds after placement, dealing 1.5♥︎ of true damage to all players in the explosion. Max 7 held.");
        addEnchant("TNT", "III", false, "Spawn with 3 TNT. Gain 1 TNT on kill. TNT explodes 1.5 seconds after placement, dealing 2♥︎ of true damage to all players in the explosion. Max 7 held.");
        addEnchant("Assassin", "I", true, "If shot while sneaking, teleport directly behind the attacker. 10 second cooldown. If this enchant would teleport you to an invalid location, such as inside a wall, teleport to the attacker instead.");
        addEnchant("Assassin", "II", true, "If attacked while sneaking, teleport directly behind the attacker. 5 second cooldown. If this enchant would teleport you to an invalid location, such as inside a wall, teleport to the attacker instead.");
        addEnchant("Assassin", "III", true, "If attacked while sneaking, teleport directly behind the attacker. 3 second cooldown. If this enchant would teleport you to an invalid location, such as inside a wall, teleport to the attacker instead.");
        addEnchant("Divine Miracle", "I", true, "10% chance to save your mystics' lives on death. Overridden by Divine Intervention .");
        addEnchant("Divine Miracle", "II", true, "20% chance to save your mystics' lives on death. Overridden by Divine Intervention .");
        addEnchant("Divine Miracle", "III", true, "30% chance to save your mystics' lives on death. Overridden by Divine Intervention .");
        addEnchant("Escape Pod", "I", true, "When hit below 2♥︎ , launch into the air, dealing 1♥︎ true damage to nearby players and gaining Regeneration II (0:20). Only works once per life.");
        addEnchant("Escape Pod", "II", true, "When hit below 2♥︎ , launch into the air, dealing 2♥︎ true damage to nearby players and gaining Regeneration III (0:25). Only works once per life.");
        addEnchant("Escape Pod", "III", true, "When hit below 2♥︎ , launch into the air, dealing 3♥︎ true damage to nearby players and gaining Regeneration IV (0:30). Only works once per life.");
        addEnchant("Gomraw's Heart", "I", true, "Heal to full when exiting combat.");
        addEnchant("Gomraw's Heart", "II", true, "Heal to full after 15 seconds out of combat. When re-entering combat, gain Regeneration IV (0:01).");
        addEnchant("Gomraw's Heart", "III", true, "Heal to full after 15 seconds out of combat. When re-entering combat, gain Regeneration IV (0:02).");
        addEnchant("Instaboom", "I", true, "Spawn with 1 Instaboom TNT. It explodes instantly, dealing 0.25♥︎ damage to all players nearby except yourself and dealing large knockback. If you hit yourself more than once in 2 seconds, 0.5♥︎ damage is dealt to yourself, doubling every consecutive use. Gain 1 Instaboom TNT on kill. Can hold 2 max.");
        addEnchant("Instaboom", "II", true, "Spawn with 1 Instaboom TNT. It explodes instantly, dealing 0.5♥︎ damage to all players nearby except yourself and dealing large knockback. If you hit yourself more than once in 2 seconds, 0.5♥︎ damage is dealt to yourself, doubling every consecutive use. Gain 1 Instaboom TNT on kill. Can hold 4 max.");
        addEnchant("Instaboom", "III", true, "Spawn with 2 Instaboom TNT. It explodes instantly, dealing 0.75♥︎ damage to all players nearby except yourself and dealing large knockback. If you hit yourself more than once in 2 seconds, 0.5♥︎ damage is dealt to yourself, doubling every consecutive use. Gain 2 Instaboom TNT on kill. Can hold 6 max.");
        addEnchant("Martyrdom", "I", true, "When dying, spawn 10 creepers.");
        addEnchant("Martyrdom", "II", true, "When dying, spawn 20 creepers.");
        addEnchant("Martyrdom", "III", true, "When dying, spawn 40 creepers.");
        addEnchant("Phoenix", "I", true, "Instead of dying, consume 1 life on these pants and regain full health. Only works once per life.");
        addEnchant("Phoenix", "II", true, "Instead of dying, consume 1 life on these pants, regain full health, and deal +10% damage for 12 seconds. Only works once per life.");
        addEnchant("Phoenix", "III", true, "Instead of dying, consume 1 life on these pants, regain full health, and deal +30% damage for 12 seconds. Only works once per life.");
        addEnchant("Pit Blob", "I", true, "Killing players summons the Blob, a size 2 slime who attacks nearby players. Every 4 kills, the blob grows one size and regains all health if it is not already the maximum size of 9.");
        addEnchant("Pit Blob", "II", true, "Killing players summons the Blob, a size 2 slime who attacks nearby players. Every 3 kills, the blob grows one size and regains all health if it is not already the maximum size of 9.");
        addEnchant("Pit Blob", "III", true, "Killing players summons the Blob, a size 2 slime who attacks nearby players. Every 2 kills, the blob grows one size and regains all health if it is not already the maximum size of 9.");
        addEnchant("Retro-Gravity Microcosm", "I", true, "If hit three times in a row by a player who is not on the ground: Heal for 1.25♥︎ . If hit from above ground within 1 second of another valid hit, do not increment the counter. If attacked from the ground, reset the counter.");
        addEnchant("Retro-Gravity Microcosm", "II", true, "If hit three times in a row by a player who is not on the ground: Heal for 1.25♥︎ . Deal 1.5♥︎ more damage on all your attacks to them for 30 seconds (stacking). If hit from above ground within 1 second of another valid hit, do not increment the counter. If attacked from the ground, reset the counter.");
        addEnchant("Retro-Gravity Microcosm", "III", true, "If hit three times in a row by a player who is not on the ground: Heal for 1.25♥︎ . Deal 1.5♥︎ more damage on all your attacks to them for 30 seconds (stacking). Deal 0.5♥︎ of true damage to them. If hit from above ground within 1 second of another valid hit, do not increment the counter. If attacked from the ground, reset the counter.");
        addEnchant("Singularity", "I", true, "The most damage you can take at once is 2.5♥︎ . This mystic does not affect true damage.");
        addEnchant("Singularity", "II", true, "The most damage you can take at once is 2♥︎ . This mystic does not affect true damage.");
        addEnchant("Singularity", "III", true, "The most damage you can take at once is 1.5♥︎ . This mystic does not affect true damage.");
        addEnchant("Solitude", "I", true, "If there is only one or fewer other players within 7 blocks, take −40% damage.");
        addEnchant("Solitude", "II", true, "If there are only two or fewer other players within 7 blocks, take −50% damage.");
        addEnchant("Solitude", "III", true, "If there are only two or fewer other players within 7 blocks, take −60% damage.");
        addEnchant("Snowballs", "I", true, "Spawn with 8 snowballs. Gain 8 snowballs on kill, max of 16 held. Snowballs apply Slowness I (0:03). Snowball hits within 5 seconds of each other \"combo,\" playing a higher-pitched music note on hit until it reaches a 5-hit combo, dealing 0.5♥︎ true damage and resetting the combo.");
        addEnchant("Snowballs", "II", true, "Spawn with 8 snowballs. Set to 16 snowballs on kill. Snowballs apply Slowness I (0:04). Snowball hits within 5 seconds of each other \"combo,\" playing a higher-pitched music note on hit until it reaches a 4-hit combo, dealing 0.5♥︎ true damage and resetting the combo.");
        addEnchant("Snowballs", "III", true, "Spawn with 16 snowballs. Refill on kill. Snowballs apply Slowness I (0:05). Snowball hits within 5 seconds of each other \"combo,\" playing a higher-pitched music note on hit until it reaches a 3-hit combo, dealing 0.5♥︎ true damage and resetting the combo.");
        addEnchant("Snowmen Army", "I", true, "Spawn with 3 snow blocks. Gain 1 on kill, max of 6 held. Hold and right-click to consume 3 blocks to summon a snowman for 30 seconds.");
        addEnchant("Snowmen Army", "II", true, "Spawn with 3 snow blocks. Gain 2 on kill, max of 9 held. Hold and right-click to consume 3 blocks to summon a snowman for 30 seconds.");
        addEnchant("Snowmen Army", "III", true, "Spawn with 3 snow blocks. Gain 3 on kill, max of 12 held. Hold and right-click to consume 3 blocks to summon a snowman for 30 seconds.");
        addEnchant("Wolf Pack", "I", true, "Spawn a wolf with 5♥ every 4 kills. Wolves deal 1.5♥ damage. Max 5 wolves.");
        addEnchant("Wolf Pack", "II", true, "Spawn a wolf with 5♥ every 3 kills. Wolves deal 1.5♥ damage. Max 7 wolves.");
        addEnchant("Wolf Pack", "III", true, "Spawn a wolf with 5♥ every 3 kills. Wolves deal 1.5♥ damage. Max 9 wolves.");
        addEnchant("Pit MBA", "I", false, "If there are at least 5 players within 15 blocks of you, gain +10% gold and +10% XP on kill.");
        addEnchant("Pit MBA", "II", false, "If there are at least 5 players within 15 blocks of you, gain +30% gold and +20% XP on kill.");
        addEnchant("Pit MBA", "III", false, "If there are at least 5 players within 15 blocks of you, gain +50% gold and +30% XP on kill.");
        addEnchant("Fractional Reserve", "I", false, "Take −1% damage per 10,000g you currently have, max of −15% (150,000g) .");
        addEnchant("Fractional Reserve", "II", false, "Take −1% damage per 10,000g you currently have, max of −21% (210,000g) .");
        addEnchant("Fractional Reserve", "III", false, "Take −1% damage per 10,000g you currently have, max of −30% (300,000g) .");
        addEnchant("Paparazzi", "I", true, "Gain 50% more rewards from major events (rounds down). Consume 2 lives of this item per major event.");
        addEnchant("Paparazzi", "II", true, "Gain 100% more rewards from major events (rounds down). Consume 2 lives of this item per major event.");
        addEnchant("Paparazzi", "III", true, "Gain 150% more rewards from major events (rounds down). Consume 2 lives of this item per major event.");
        addEnchant("Double-jump", "I", true, "Pressing the jump button in midair launches you in the direction you are facing. 20 second cooldown.");
        addEnchant("Double-jump", "II", true, "Pressing the jump button in midair launches you in the direction you are facing. 10 second cooldown.");
        addEnchant("Double-jump", "III", true, "Pressing the jump button in midair launches you in the direction you are facing. 5 second cooldown.");
        addEnchant("Somber", "N/A", false, "You are unaffected by mystical enchantments. You cannot use mystical enchantments.");
        addEnchant("Grim Reaper", "N/A", false, "If a player dies within 10 blocks, deal 2♥︎ to them and earn that damage as an assist on their death. Earn −80% gold and XP from kills.");
        addEnchant("Hedge Fund", "N/A", false, "Earn +6g from kills. Earn +66g instead if the target was wearing enchanted Mystic Pants of any type. Lose 50g when dying.");
        addEnchant("Lycanthropy", "N/A", false, "At nighttime, gain permanent Speed I, Regeneration II and earn +10% gold and +10% XP . The day after you wear these pants, you cannot gain the Speed effect.");
        addEnchant("Mind Assault", "N/A", false, "Deal −60% damage. After this debuff is applied, deal +0.75♥︎ more damage per player wearing leather armor within 12 blocks (including yourself). Max of +8♥︎ .");
        addEnchant("Misery", "N/A", false, "If your target is wearing leather pants, deal +0.5♥︎ of true damage to them on all your hits. Take 0.3♥︎ true damage on all hits received.");
        addEnchant("Needless Suffering", "N/A", false, "Respawn with 30♥︎ of Absorption. Cannot heal by any method. Must be killed by another player once while wearing these pants to gain Absorption.");
        addEnchant("Sanguisuge", "N/A", false, "Heal 0.5♥︎ when hitting a player who is wearing leather armor (2s cooldown). Heal 1♥︎ instead if the Vampire perk is equipped. The Regeneration effect has no effect on the user.");
        addEnchant("Spite", "N/A", false, "Deal +20% damage to players wearing leather armor but take +5% damage from them.");
        addEnchant("Combo: Venom", "N/A", true, "Every third hit poisons the target for 12 seconds and yourself for 24 seconds. Poison does not deal damage. While poisoned, players receive the Somber effect.");
        addEnchant("Golden Handcuffs", "N/A", true, "When the user claims a bounty , 4× the bounty is shared between all players on the server. Requires 30 players in the server to activate.");
        addEnchant("Heartripper", "N/A", true, "Every life removed from a mystic through killing while wearing these pants grants these pants +1 bloodshard. Earning 27 bloodshards grants 1 pair of Fresh P a n t s of a random standard color and resets the bloodshard count to 0, regardless of how many mystic lives the last player killed lost. Consume 2 lives of this item when generating Fresh Pants. If these pants would have 0 or fewer lives after generating Fresh Pants, they are converted to Fresh Dark Pants. When Dark Pants gain this enchant on upgrade, their max lives do not increase.");
        addEnchant("Nostalgia", "N/A", true, "Take −10% damage. Diamond armor worn glows as if enchanted.");
        addEnchant("Beat the Spammers", "I", false, "Deal 10% more damage to players holding bows.");
        addEnchant("Beat the Spammers", "II", false, "Deal 25% more damage to players holding bows.");
        addEnchant("Beat the Spammers", "III", false, "Deal 40% more damage to players holding bows.");
        addEnchant("Bounty Reaper", "I", false, "Deal 7% more damage to bountied players.");
        addEnchant("Bounty Reaper", "II", false, "Deal 15% more damage to bountied players.");
        addEnchant("Bounty Reaper", "III", false, "Deal 25% more damage to bountied players.");
        addEnchant("Combo: Damage", "I", false, "Every fourth hit deals 20% more damage.");
        addEnchant("Combo: Damage", "II", false, "Every third hit deals 30% more damage.");
        addEnchant("Combo: Damage", "III", false, "Every third hit deals 45% more damage.");
        addEnchant("Diamond Stomp", "I", false, "Deal 6% more damage to players wearing diamond armor.");
        addEnchant("Diamond Stomp", "II", false, "Deal 12% more damage to players wearing diamond armor.");
        addEnchant("Diamond Stomp", "III", false, "Deal 25% more damage to players wearing diamond armor.");
        addEnchant("Fancy Raider", "I", false, "Deal 5% more damage to players wearing leather armor.");
        addEnchant("Fancy Raider", "II", false, "Deal 9% more damage to players wearing leather armor.");
        addEnchant("Fancy Raider", "III", false, "Deal 16% more damage to players wearing leather armor.");
        addEnchant("Grasshopper", "I", false, "Deal 5% more damage when you are standing on grass.");
        addEnchant("Grasshopper", "II", false, "Deal 9% more damage when you are standing on grass.");
        addEnchant("Grasshopper", "III", false, "Deal 15% more damage when you are standing on grass.");
        addEnchant("Gold and Boosted", "I", false, "Deal 5% more damage while you have absorption hearts.");
        addEnchant("Gold and Boosted", "II", false, "Deal 9% more damage while you have absorption hearts.");
        addEnchant("Gold and Boosted", "III", false, "Deal 15% more damage while you have absorption hearts.");
        addEnchant("King Buster", "I", false, "Deal 7% more damage to players with more than 50% health.");
        addEnchant("King Buster", "II", false, "Deal 13% more damage to players with more than 50% health.");
        addEnchant("King Buster", "III", false, "Deal 20% more damage to players with more than 50% health.");
        addEnchant("Pain Focus", "I", false, "Deal 1% more damage per ♥︎ you're missing.");
        addEnchant("Pain Focus", "II", false, "Deal 2% more damage per ♥︎ you're missing.");
        addEnchant("Pain Focus", "III", false, "Deal 5% more damage per ♥︎ you're missing.");
        addEnchant("Punisher", "I", false, "Deal 6% more damage to players with less than 50% health.");
        addEnchant("Punisher", "II", false, "Deal 12% more damage to players with less than 50% health.");
        addEnchant("Punisher", "III", false, "Deal 18% more damage to players with less than 50% health.");
        addEnchant("Shark", "I", false, "Deal 2% more damage per player within 12 blocks below 6♥︎ .");
        addEnchant("Shark", "II", false, "Deal 4% more damage per player within 12 blocks below 6♥︎ .");
        addEnchant("Shark", "III", false, "Deal 7% more damage per player within 12 blocks below 6♥︎ .");
        addEnchant("Sharp", "I", false, "Deal 4% more damage.");
        addEnchant("Sharp", "II", false, "Deal 7% more damage.");
        addEnchant("Sharp", "III", false, "Deal 12% more damage.");
        addEnchant("Combo: XP", "I", false, "Every fifth hit, gain +20 XP .");
        addEnchant("Combo: XP", "II", false, "Every fifth hit, gain +28 XP .");
        addEnchant("Combo: XP", "III", false, "Every fifth hit, gain +36 XP .");
        addEnchant("Pitpocket", "I", false, "Steal 15g from the target on hit. 25 second cooldown.");
        addEnchant("Pitpocket", "II", false, "Steal 20g from the target on hit. 20 second cooldown.");
        addEnchant("Pitpocket", "III", false, "Steal 25g from the target on hit. 13 second cooldown.");
        addEnchant("Sierra", "I", false, "Earn +30 gold on kill per diamond piece the victim was wearing.");
        addEnchant("Sierra", "II", false, "Earn +60 gold on kill per diamond piece the victim was wearing.");
        addEnchant("Sierra", "III", false, "Earn +90 gold on kill per diamond piece the victim was wearing.");
        addEnchant("Berserker", "I", false, "12% chance to deal +50% damage while standing on the ground.");
        addEnchant("Berserker", "II", false, "20% chance to deal +50% damage while standing on the ground.");
        addEnchant("Berserker", "III", false, "30% chance to deal +50% damage while standing on the ground.");
        addEnchant("Bruiser", "I", false, "While holding and blocking this sword, opponents' attacks deal −0.5♥︎ damage.");
        addEnchant("Bruiser", "II", false, "While holding and blocking this sword, opponents' attacks deal −1♥︎ damage.");
        addEnchant("Bruiser", "III", false, "While holding and blocking this sword, opponents' attacks deal −2♥︎ damage.");
        addEnchant("Bullet Time", "I", false, "While blocking this sword, arrows can't make contact with you and arrows that would make contact disappear.");
        addEnchant("Bullet Time", "II", false, "While blocking this sword, arrows can't make contact with you and arrows that would make contact disappear. Heal 1♥︎ when avoiding arrows using this sword.");
        addEnchant("Bullet Time", "III", false, "While blocking this sword, arrows can't make contact with you and arrows that would make contact disappear. Heal 1.5♥︎ when avoiding arrows using this sword.");
        addEnchant("Combo: Heal", "I", false, "Every fourth hit heals 0.4♥︎ and grants 0.4♥︎ absorption.");
        addEnchant("Combo: Heal", "II", false, "Every fourth hit heals 0.8♥︎ and grants 0.8♥︎ absorption.");
        addEnchant("Combo: Heal", "III", false, "Every fourth hit heals 1.2♥︎ and grants 1.2♥︎ absorption.");
        addEnchant("Combo: Swift", "I", false, "Every fourth hit grants Speed I (0:03).");
        addEnchant("Combo: Swift", "II", false, "Every third hit grants Speed II (0:04).");
        addEnchant("Combo: Swift", "III", false, "Every third hit grants Speed II (0:05).");
        addEnchant("Counter-Janitor", "I", false, "Gain Resistance I (0:02) on kill.");
        addEnchant("Counter-Janitor", "II", false, "Gain Resistance I (0:03) on kill.");
        addEnchant("Counter-Janitor", "III", false, "Gain Resistance I (0:05) on kill.");
        addEnchant("Crush", "I", false, "Apply Weakness V (0:00.3) to the target on hit. 1.5 second cooldown.");
        addEnchant("Crush", "II", false, "Apply Weakness VI (0:00.5) to the target on hit. 1.5 second cooldown.");
        addEnchant("Crush", "III", false, "Apply Weakness VII (0:00.7) to the target on hit. 1.5 second cooldown.");
        addEnchant("Duelist", "I", false, "Blocking two hits from the same player makes your next strike against them heal yourself for +0.5♥︎ and deal +20% damage.");
        addEnchant("Duelist", "II", false, "Blocking two hits from the same player makes your next strike against them heal yourself for +1♥︎ and deal +40% damage.");
        addEnchant("Duelist", "III", false, "Blocking two hits from the same player makes your next strike against them heal yourself for +1.5♥︎ and deal +75% damage.");
        addEnchant("Guts", "I", false, "Heal 0.25♥︎ on kill.");
        addEnchant("Guts", "II", false, "Heal 0.5♥︎ on kill.");
        addEnchant("Guts", "III", false, "Heal 1♥︎ on kill.");
        addEnchant("Lifesteal", "I", false, "Heal 4% of damage dealt (before armor is applied) on hit. Maximum of 1.5♥︎ healed per hit. Initial attack must deal 18.75♥ , or +400% damage, to reach the maximum.");
        addEnchant("Lifesteal", "II", false, "Heal 8% of damage dealt (before armor is applied) on hit. Maximum of 1.5♥︎ healed per hit. Initial attack must deal 9.375♥ , or +150% damage, to reach the maximum.");
        addEnchant("Lifesteal", "III", false, "Heal 13% of damage dealt (before armor is applied) on hit. Maximum of 1.5♥︎ healed per hit. Initial attack must deal 5.769♥ , or +54% damage, to reach the maximum.");
        addEnchant("Revengeance", "I", false, "Deal 8% more damage to the last player that killed you. You must be holding this sword on death or have attacked the player for this enchantment to activate. The player will be marked with anger particles.");
        addEnchant("Revengeance", "II", false, "Deal 15% more damage to the last player that killed you. You must be holding this sword on death or have attacked the player for this enchantment to activate. The player will be marked with anger particles.");
        addEnchant("Revengeance", "III", false, "Deal 25% more damage to the last player that killed you. You must be holding this sword on death or have attacked the player for this enchantment to activate. The player will be marked with anger particles.");
        addEnchant("Speedy Kill", "I", false, "Gain Speed I (0:04) on kill.");
        addEnchant("Speedy Kill", "II", false, "Gain Speed I (0:07) on kill.");
        addEnchant("Speedy Kill", "III", false, "Gain Speed I (0:12) on kill.");
        addEnchant("Billionaire", "I", true, "This sword deals +33.3% damage but lose 100g on hit. No effect if the user has less than 100g.");
        addEnchant("Billionaire", "II", true, "This sword deals +66.7% damage but lose 200g on hit. No effect if the user has less than 200g.");
        addEnchant("Billionaire", "III", true, "This sword deals +100% damage but lose 350g on hit. No effect if the user has less than 350g.");
        addEnchant("Combo: Perun's Wrath", "I", true, "Every fifth hit strikes lightning dealing 1.5♥︎ of true damage.");
        addEnchant("Combo: Perun's Wrath", "II", true, "Every fourth hit strikes lightning dealing 2♥︎ of true damage.");
        addEnchant("Combo: Perun's Wrath", "III", true, "Every fourth hit strikes lightning dealing 1♥︎ of true damage + 1♥︎ per diamond piece the target is wearing.");
        addEnchant("Combo: Stun", "I", true, "Every fifth hit applies Slowness VIII, Mining Fatigue XI and Jump Boost I to the target for 0.5s. 8s cooldown per player.");
        addEnchant("Combo: Stun", "II", true, "Every fifth hit applies Slowness VIII, Mining Fatigue XI and Jump Boost I to the target for 0.8s. 8s cooldown per player.");
        addEnchant("Combo: Stun", "III", true, "Every fifth hit applies Slowness VIII, Mining Fatigue XI and Jump Boost I to the target for 1.2s. 8s cooldown per player.");
        addEnchant("Executioner", "I", true, "When hitting a player to under 1♥︎ , deal 1♥︎ of true damage to them.");
        addEnchant("Executioner", "II", true, "When hitting a player to under 1.5♥︎ , deal 1.5♥︎ of true damage to them.");
        addEnchant("Executioner", "III", true, "When hitting a player to under 2♥︎ , deal 2♥︎ of true damage to them.");
        addEnchant("Gamble", "I", true, "When hitting a player, there is a 50/50 chance to hit either yourself or the target for 1♥︎ of true damage. If you take the true damage, you cannot avoid it even with true damage immunity.");
        addEnchant("Gamble", "II", true, "When hitting a player, there is a 50/50 chance to hit either yourself or the target for 2♥︎ of true damage. If you take the true damage, you cannot avoid it even with true damage immunity.");
        addEnchant("Gamble", "III", true, "When hitting a player, there is a 50/50 chance to hit either yourself or the target for 3♥︎ of true damage. If you take the true damage, you cannot avoid it even with true damage immunity.");
        addEnchant("Healer", "I", true, "Hitting a player heals the user for 0.5♥︎ and the target for 2♥︎ . 1 second cooldown.");
        addEnchant("Healer", "II", true, "Hitting a player heals the user for 0.75♥︎ and the target for 4♥︎ . 1 second cooldown.");
        addEnchant("Healer", "III", true, "Hitting a player heals the user for 1♥︎ and the target for 5♥︎ . 1 second cooldown.");
        addEnchant("Hemorrhage", "I", true, "Attacking a player hemorrhages them for 4 seconds, preventing them from gaining more Absorption and applying Slowness I. 6s cooldown.");
        addEnchant("Hemorrhage", "II", true, "Attacking a player hemorrhages them for 4 seconds, preventing them from gaining more Absorption and applying Slowness I. 4s cooldown.");
        addEnchant("Hemorrhage", "III", true, "Attacking a player hemorrhages them for 5 seconds, preventing them from gaining more Absorption and applying Slowness I. 2s cooldown.");
        addEnchant("Knockback", "I", true, "Attacks knock players back about 3 blocks farther than usual.");
        addEnchant("Knockback", "II", true, "Attacks knock players back about 6 blocks farther than usual.");
        addEnchant("Knockback", "III", true, "Attacks knock players back about 9 blocks farther than usual.");
        addEnchant("Speedy Hit", "I", true, "Gain Speed I (0:05) on hit. 3 second cooldown.");
        addEnchant("Speedy Hit", "II", true, "Gain Speed I (0:07) on hit. 2 second cooldown.");
        addEnchant("Speedy Hit", "III", true, "Gain Speed I (0:09) on hit. 1 second cooldown.");
        addEnchant("The Punch", "I", true, "Launch targets 60 blocks into the air on hit. 30 second cooldown.");
        addEnchant("The Punch", "II", true, "Launch targets 60 blocks into the air on hit. 25 second cooldown.");
        addEnchant("The Punch", "III", true, "Launch targets 60 blocks into the air on hit. 20 second cooldown.");
        addEnchant("Hidden Jewel", "N/A", false, "If 117 players are killed with this sword without dying, this sword turns into a Tier I Sword with 3 or 5 lives and a random Tier III non-resource enchant. Returning to spawn without dying does not reset the kills.");
        addEnchant("Bottomless Quiver", "I", false, "Receive 1 arrow on arrow hit.");
        addEnchant("Bottomless Quiver", "II", false, "Receive 3 arrows on arrow hit.");
        addEnchant("Bottomless Quiver", "III", false, "Receive 8 arrows on arrow hit.");
        addEnchant("First Shot", "I", false, "First arrow shot on a player deals +10% damage.");
        addEnchant("First Shot", "II", false, "First arrow shot on a player deals +16% damage.");
        addEnchant("First Shot", "III", false, "First arrow shot on a player deals +25% damage.");
        addEnchant("Fletching", "I", false, "Deal +7% arrow damage.");
        addEnchant("Arrow Armory", "I", false, "Consume 3 arrows on shot but deal +12% arrow damage.");
        addEnchant("Arrow Armory", "II", false, "Consume 5 arrows on shot but deal +25% arrow damage.");
        addEnchant("Arrow Armory", "III", false, "Consume 8 arrows on shot but deal +60% arrow damage.");
        addEnchant("Chipping", "I", false, "Arrows deal 0.5♥︎ of true damage before applying arrow damage.");
        addEnchant("Chipping", "II", false, "Arrows deal 1♥︎ of true damage before applying arrow damage.");
        addEnchant("Chipping", "III", false, "Arrows deal 1.5♥︎ of true damage before applying arrow damage.");
        addEnchant("Faster than their shadow", "I", false, "Landing 3 arrows without missing grants Speed II (0:04).");
        addEnchant("Faster than their shadow", "II", false, "Landing 2 arrows without missing grants Speed III (0:04).");
        addEnchant("Faster than their shadow", "III", false, "Landing 2 arrows without missing grants Speed IV (0:04).");
        addEnchant("Mixed Combat", "I", false, "After landing a bow hit, deal +10% damage on your next melee strike with this bow.");
        addEnchant("Mixed Combat", "II", false, "After landing a bow hit, deal +20% damage on your next melee strike with this bow.");
        addEnchant("Mixed Combat", "III", false, "After landing a bow hit, deal +30% damage on your next melee strike with this bow.");
        addEnchant("Parasite", "I", false, "Heal 0.25♥︎ on arrow hit.");
        addEnchant("Parasite", "II", false, "Heal 0.5♥︎ on arrow hit.");
        addEnchant("Parasite", "III", false, "Heal 1♥︎ on arrow hit.");
        addEnchant("Pin down", "I", false, "Fully charged shots pin targets down, removing and preventing them from gaining Speed or Jump Boost for 3s.");
        addEnchant("Pin down", "II", false, "Fully charged shots pin targets down, removing and preventing them from gaining Speed or Jump Boost for 5s.");
        addEnchant("Pin down", "III", false, "Fully charged shots pin targets down, removing and preventing them from gaining Speed or Jump Boost for 10s.");
        addEnchant("Push comes to shove", "I", false, "Every third arrow hit has the vanilla Punch III effect.");
        addEnchant("Push comes to shove", "II", false, "Every third arrow hit deals +0.5♥︎ damage and has the vanilla Punch V effect.");
        addEnchant("Push comes to shove", "III", false, "Every third arrow hit deals +1♥︎ damage and has the vanilla Punch VII effect.");
        addEnchant("Sprint Drain", "I", false, "Arrow hits grant Speed I (0:03).");
        addEnchant("Sprint Drain", "II", false, "Arrow hits grant Speed I (0:05) and apply Slowness I (0:03) to the target.");
        addEnchant("Sprint Drain", "III", false, "Arrow hits grant Speed II (0:07) and apply Slowness I (0:03) to the target.");
        addEnchant("What doesn't kill you", "I", false, "Heal 1.5♥︎ when shooting yourself. 3 second cooldown.");
        addEnchant("What doesn't kill you", "II", false, "Heal 2.5♥︎ when shooting yourself. 3 second cooldown.");
        addEnchant("What doesn't kill you", "III", false, "Heal 3.5♥︎ when shooting yourself. 3 second cooldown.");
        addEnchant("Wasp", "I", false, "Shots apply Weakness II (0:06) to the target.");
        addEnchant("Wasp", "II", false, "Shots apply Weakness III (0:11) to the target.");
        addEnchant("Wasp", "III", false, "Shots apply Weakness IV (0:16) to the target.");
        addEnchant("Devil Chicks!", "I", true, "Arrows spawn an explosive chicken. Chickens deal large knockback and 0.6♥︎ of true damage to players in the explosion.");
        addEnchant("Devil Chicks!", "II", true, "Arrows spawn 2 explosive chickens. Chickens deal large knockback and 0.6♥︎ of true damage to players in the explosion.");
        addEnchant("Devil Chicks!", "III", true, "Arrows spawn 3 explosive chickens. Chickens deal large knockback and 0.6♥︎ of true damage to players in the explosion.");
        addEnchant("Explosive", "I", true, "Arrows create a small explosion on impact, knocking players back and dealing 0.5♥︎ of true damage. 5 second cooldown.");
        addEnchant("Explosive", "II", true, "Arrows create a minor explosion on impact, knocking players back and dealing 1♥︎ of true damage. 3 second cooldown.");
        addEnchant("Explosive", "III", true, "Arrows create a huge explosion on impact, knocking players back and dealing 1.5♥︎ of true damage. 5 second cooldown.");
        addEnchant("Lucky Shot", "I", true, "2% chance to fire an arrow with a gold trail. These arrows deal +300% damage.");
        addEnchant("Lucky Shot", "II", true, "5% chance to fire an arrow with a gold trail. These arrows deal +300% damage.");
        addEnchant("Lucky Shot", "III", true, "10% chance to fire an arrow with a gold trail. These arrows deal +300% damage.");
        addEnchant("Mega Longbow", "I", true, "Shots are automatically fully drawn and grant Jump Boost II (0:02). 1 second cooldown.");
        addEnchant("Mega Longbow", "II", true, "Shots are automatically fully drawn and grant Jump Boost III (0:02). 1 second cooldown.");
        addEnchant("Mega Longbow", "III", true, "Shots are automatically fully drawn and grant Jump Boost IV (0:02). 1 second cooldown.");
        addEnchant("Pullbow", "I", true, "Shooting a player pulls them slightly towards you. 8 second cooldown per player.");
        addEnchant("Pullbow", "II", true, "Shooting a player pulls them and all nearby players towards you. 5 second cooldown per player.");
        addEnchant("Pullbow", "III", true, "Shooting a player pulls them and all nearby players with high force towards you. 5 second cooldown per player.");
        addEnchant("Telebow", "I", true, "Sneak to fire a teleportation arrow. Teleport to where the arrow lands. 90 second cooldown, minus 3 for every arrow landed during the cooldown.");
        addEnchant("Telebow", "II", true, "Sneak to fire a teleportation arrow. Teleport to where the arrow lands. 45 second cooldown, minus 3 for every arrow landed during the cooldown.");
        addEnchant("Telebow", "III", true, "Sneak to fire a teleportation arrow. Teleport to where the arrow lands. 20 second cooldown, minus 3 for every arrow landed during the cooldown.");
        addEnchant("True Shot", "I", true, "25% of the arrow's damage is dealt as true damage.");
        addEnchant("True Shot", "II", true, "35% of the arrow's damage plus 0.25♥︎ is dealt as true damage.");
        addEnchant("True Shot", "III", true, "45% of the arrow's damage plus 0.5♥︎ is dealt as true damage.");
        addEnchant("Volley", "I", true, "After firing an arrow, automatically fire 2 extra arrows in quick succession. Extra arrows don't consume arrows from your inventory.");
        addEnchant("Volley", "II", true, "After firing an arrow, automatically fire 3 extra arrows in quick succession. Extra arrows don't consume arrows from your inventory.");
        addEnchant("Volley", "III", true, "After firing an arrow, automatically fire 4 extra arrows in quick succession. Extra arrows don't consume arrows from your inventory.");
        addEnchant("Robinhood", "I", true, "Fully charged shots are homing but deal −60% damage.");
        addEnchant("Robinhood", "II", true, "Fully charged shots are homing but deal −50% damage.");
        addEnchant("Robinhood", "III", true, "Fully charged shots are homing but deal −40% damage.");
        addEnchant("Golden Helmet", "N/A", false, "Earn +10% XP from kills. As strong as diamond.");
        addEnchant("Archangel Chestplate", "N/A", false, "Receive −10% damage Angel Faction Reward");
        addEnchant("Armageddon Boots", "N/A", false, "Your hits ignore Somber Demon Faction Reward");
    }

    private static void addPrestige(String prestige, String multiplier, String xpToPrestige, String totalXp, String goldToNext, String color, String format) {
        PRESTIGES.put(prestige.toUpperCase(), new PrestigeData(prestige, multiplier, xpToPrestige, totalXp, goldToNext, color, format));
    }

    private static void addEnchant(String name, String tier, boolean isRare, String description) {
        ENCHANTS.add(new PitEnchant(name, tier, isRare, description));
    }

    public static PrestigeData getPrestige(String prestige) {
        if (prestige == null) return null;
        return PRESTIGES.get(prestige.toUpperCase());
    }

    public static PitEnchant getEnchant(String name, String tier) {
        for (PitEnchant e : ENCHANTS) {
            if (e.name.equalsIgnoreCase(name) && e.tier.equalsIgnoreCase(tier)) {
                return e;
            }
        }
        return null;
    }

    public static List<PitEnchant> getAllEnchants() {
        return ENCHANTS;
    }

    public static class PrestigeData {
        public final String prestige, multiplier, xpToPrestige, totalXpNeeded, goldToNext, bracketColor, formatting;
        public PrestigeData(String prestige, String multiplier, String xpToPrestige, String totalXpNeeded, String goldToNext, String bracketColor, String formatting) {
            this.prestige = prestige; this.multiplier = multiplier; this.xpToPrestige = xpToPrestige; this.totalXpNeeded = totalXpNeeded; this.goldToNext = goldToNext; this.bracketColor = bracketColor; this.formatting = formatting;
        }
    }

    public static class PitEnchant {
        public final String name, tier, description; public final boolean isRare;
        public PitEnchant(String name, String tier, boolean isRare, String description) {
            this.name = name; this.tier = tier; this.isRare = isRare; this.description = description;
        }
    }
}